language: generic

sudo: required
servides:
  - docker

before_install:
  - docker build -t gabi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabi/docker-react npm run test -- --coverage